annotations:
  category: Analytics
apiVersion: v1
appVersion: 7.9.1
description: A highly scalable open-source full-text search and analytics engine
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch
icon: https://bitnami.com/assets/stacks/elasticsearch/img/elasticsearch-stack-110x117.png
keywords:
- elasticsearch
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: elasticsearch
sources:
- https://github.com/bitnami/bitnami-docker-elasticsearch
- https://www.elastic.co/products/elasticsearch
version: 12.6.3
